### ISSUE TITLE
Add nside2order, order2nside

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#163]
Could `order2nside` and `nside2order` methods be added? The former is trivial (it's just `1<<order`) but implementing the latter in exact integer arithmetic is nontrivial and there is a slick implementation in `healpix_base.cc`.

**Comment by cjcopi** [comment]
This seems to have fallen through the cracks, but is simple to implement so might as well be done.  As noted `order2nside` is just a bit shift operation.  Similarly `nside2order` is just a logarithm base 2.  Implementing this by converting `log2` to an integer is not ideal so there seems to be at least two options

1. Use `frexp` as in `np.frexp(nside)[1]-1`,
2. Use `ilog2`.  A nice implementation of this is in Healpix math_utils.h which can be directly converted to Python.

Option 1 has the side effect of working with floats and arrays automatically.  `ilog2` is based on bit shifting so would require more work to vectorize.

Is there a preferred implementation?

**Comment by zonca** [comment]
I prefer 1, better to have less code to maintain

**Comment by mreineck** [comment]
On 07/07/15 23:45, Andrea Zonca wrote:
> I prefer 1, better to have less code to maintain
>
But please be careful about rounding errors with frexp! For very large
integers there is no exact floating point representation, and you might
get wrong results.

Cheers,
  Martin

**Comment by cjcopi** [comment]
> But please be careful about rounding errors with frexp! For very large integers there is no exact floating point representation, and you might get wrong results.

This is a general concern with using floating point routines, but is it a concern here?  Do you have an example?  Without having looked at the code for frexp I was under the impression it was safer in this regard.  This is particularly true given that nside is a power of 2.

In testing (only on 64 bit Linux) `np.frexp` returns the correct answer up to `order=63` after which it throws an error due to conversion issues.  Interestingly `math.frexp` works up to `order=1023` before it throws an error.

At present in healpy `check_nside` restricts the order to less than 30 so perhaps this is a moot point.

**Comment by mreineck** [comment]
The potential rounding is not a problem in this concrete situation. I just wanted to warn about replacing the general-purpose ilog2 with a frexp-based approach. As long as the frexp call is performed on numbers known to be powers of 2, everything is fine.
However if healpy should ever be enhanced to support non-power-of-2 values for Nside (in RING scheme only, of course), then the nside2order function will have to return -1 for such inputs in order to be analogous to the C++ version.

**Comment by lpsinger** [comment]
I think that the best reason not to use `frexp` is that the inputs to this function ought to be integers, so an algorithm that is exact for any valid integer is preferable.

**Comment by mreineck** [comment]
In that case, I expect that Python has a function returning the number of leading zeros in the binary representation of an integer. From this it's fairly straightforward to get ilog2.
The C++ standard does not specify such a function, so Healpix C++ only uses it when it is being compiled by g++, which provides it as an extension.

**Comment by cjcopi** [comment]
Ok, avoiding `frexp` one could instead use
`nside.bit_length()-1`
which only works for integers, not floats or arrays.

Regardless of the algorithm used if nside can be a non-power-of-2 then `nside2order` will need to be changed to detect this.

**Comment by lpsinger** [comment]
> Regardless of the algorithm used if nside can be a non-power-of-2 then nside2order will need to be changed to detect this.

That is not the case currently. `nside2npix` and friends will reject arguments that correspond to non-power-of-2 `nside`, so it is best for now if these two new functions also treat that as an error.

**Comment by cjcopi** [comment]
> That is not the case currently. nside2npix and friends will reject arguments that correspond to non-power-of-2 nside, so it is best for now if these two new functions also treat that as an error.

Correct, what I meant is that currently `check_nside` handles this and throws an error.  But if this function were to accept a non-power-of-2 then this would not be a sufficient check anymore as `nside2order` would then have a more stringent requirement.

**Comment by lpsinger** [comment]
Fixed in #266.
