### ISSUE TITLE
Install healpy failing

### ISSUE THREAD

**Issue by sabrinacales** [healpy/healpy#224]
Hello, 

I tried using 'pip install --user healpy' to install healpy and get the error:

'''
Command /Users/bri/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/g7/qgrhr58s6lb9b3tw7qt26_9c0000gn/T/pip_build_bri/healpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/g7/qgrhr58s6lb9b3tw7qt26_9c0000gn/T/pip-6IW0T7-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /private/var/folders/g7/qgrhr58s6lb9b3tw7qt26_9c0000gn/T/pip_build_bri/healpy
Storing debug log for failure in /Users/bri/.pip/pip.log
'''

Then I tried:

'sudo port install py27-healpy', which seemed install cleanly, but when I tried to use healpy in the python notebook I got this: 'ImportError: No module named healpy'. So I suspect it didn't install properly after all. 

Hints?

Mac OS 10.9.5
MacPorts base version 2.3.3
conda 3.9.0
Anaconda 2.1.0
Python 2.7.8
ipython 2.2.0

**Comment by lpsinger** [comment]
> I tried using 'pip install --user healpy' to install healpy and get the error:

Would you please post the full output of the command, in a [gist](https://gist.github.com) if it is very long?

> Then I tried:
> 
> 'sudo port install py27-healpy', which seemed install cleanly, but when I tried to use healpy in the python notebook I got this: 'ImportError: No module named healpy'. So I suspect it didn't install properly after all.

Since you are evidently a Mac user who already has MacPorts, this is certainly the fastest and simplest way to get Healpy. My guess is that you may have accidentally started Anaconda instead of the MacPorts python or ipython notebook. The Anaconda python cannot implement Python packages installed under MacPorts, or vice versa, unless you configure your path specifically to do so (and this would get pretty confusing).

MacPorts' python interpreters are called `python2.7` and `ipython2.7` so that the user can pick what Python version should be the default. Try launching Python by running `python2.7` (full path: `/opt/local/bin/python2.7`) or IPython by running `ipython2.7` (full path: `/opt/local/bin/ipython2.7`). In both cases, you should be able to import Healpy. If this works, and you are satisfied with using MacPorts as your default Python interpreter, you can set it as the default by running

    $ sudo port select --set python python27
    $ sudo port select --set ipython ipython27

which just creates `/opt/local/bin/python` and `/opt/local/bin/ipython` as symlinks to `python2.7` and `ipython2.7`.

**Comment by lpsinger** [comment]
@sabrinacales, did this work for you? If so, we can close this ticket as this seems more like a how-to question than a bug report.

**Comment by sabrinacales** [comment]
Hi Leo,

Thanks for the quick response. I haven’t been gotten to check yet. Hopefully soon.

Sabrina

**Comment by lpsinger** [comment]
Please reopen this ticket if you are still having issues.
