### ISSUE TITLE
Don't understand the l,m values output by healpy

### ISSUE THREAD

**Issue by abrahamneben** [healpy/healpy#274]
I am confused by the l and m values that get output by healpy, and how they are indexed. When I ask healpy which (l,m) values correspond to which indices in the Alm output, I find:

>>> lmax=3
>>> lvals,mvals = hp.sphtfunc.Alm.getlm(lmax,arange(hp.sphtfunc.Alm.getsize(lmax)))

>>> lvals
[0 1 2 3 1 2 3 2 3 3]
>>> mvals
 [0 0 0 0 1 1 1 2 2 3]

So there are 10 values. However I requested values up to lmax=3, so I should have (l,m)=(0,0),(1,-1),(1,0),(1,1),(2,-2),(2,-1),(2,0),(2,1),(2,2), which is only 9 instead of 10. Also, there should be one entry in lvals equal to 0, and 3 equal to 1, and 5 equal to 2. This is not what I see. What is wrong here?

**Comment by mreineck** [comment]
I think there are two misunderstandings here.
First, if you request values up to lmax=3, then you shouldn't expect 9 possible combinations of l,m, but 16. Since lmax is inclusive, there are also (l,m)=(3,-3),(3,-2),(3,-1),(3,0),(3,1),(3,2),(3,3)
Second, the A_lm processed by healpy have certain symmetry properties linking the values at (l,m) and (l,-m), so that values with negative m need not be stored, they can always be reconstructed from the counterpart with positive m. The symmetry relation is (no guarantee!) something like a(l,-m)=(-1)^m conj(a(l,m)).

**Comment by abrahamneben** [comment]
I see, that makes sense that the negative m values carry no further information in the same way that the negative frequencies in an FFT carry no further information unless the map is complex. Thanks.
