### ISSUE TITLE
Marking dependencies as optional

### ISSUE THREAD

**Issue by marius311** [healpy/healpy#312]
It would be nice to not be forced to install matplotlib (and even maybe pyfits) when you install Healpy, since there's quite a lot of functionality that works without it. Any chance something like that could be added? 

Fyi, I'm thinking of deploying an app to Cosmology@Home that uses Healpy, so since this would be getting sent out to lots of people on possibly not-very-fast internet connections, download size is really important.

**Comment by mreineck** [comment]
I can't comment on your request itself (I just do C++, not Python), but maybe a related heads-up: the Wikipedia page for Cosmology@home says that "The Cosmology@Home application is proprietary." If that is indeed the case, you may not be able to link it with healpy and distribute theresulting code because of licensing conflicts. But I admit I haven't looked at the app in any depth.

**Comment by zonca** [comment]
@marius311 that would be a good idea, however it would be important to implement a good fallback that notifies users everytime they need those packages and prompt them to install.
So that would require a significant amount of work, unless you know some package that does that automatically (?).

In any case, we can evaluate a Pull Request if you want to work on it!

**Comment by marius311** [comment]
@zonca I was afraid of that answer :) I will see if I get a chance to at any point. 

@mreineck Thanks, I'm actually the main dev of C@H, I think the only problem is that the wiki is out of date.

**Comment by lpsinger** [comment]
> So that would require a significant amount of work, unless you know some package that does that automatically (?).

You're probably looking for [setuptools extras](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

**Comment by zonca** [comment]
no updates on this, closing
