### ISSUE TITLE
Problem with installation anaconda and OSX 10.9.5

### ISSUE THREAD

**Issue by svalenti** [healpy/healpy#319]
I installed healpy using pip

the installation successfully completed, but when I import the package I get the following error:

>>> import healpy
/Users/svalenti/anaconda/lib/python2.7/site-packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/svalenti/anaconda/lib/python2.7/site-packages/healpy/__init__.py", line 42, in <module>
    from .sphtfunc import (anafast, map2alm,
  File "/Users/svalenti/anaconda/lib/python2.7/site-packages/healpy/sphtfunc.py", line 31, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: dlopen(/Users/svalenti/anaconda/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Symbol not found: _GOMP_barrier
  Referenced from: /opt/local/lib/libhealpix_cxx.0.dylib
  Expected in: flat namespace
 in /opt/local/lib/libhealpix_cxx.0.dylib

**Comment by lpsinger** [comment]
This error message means that pip linked healpy against the MacPorts build of healpix_cxx, which is built with OpenMP support. However, pip used a compiler that doesn't support OpenMP directives (probably clang).

You could use the MacPorts build of Healpy (`sudo port install py27-healpy`). Or, if you prefer using Anaconda Python, then you could uninstall or deactivate healpix_cxx (`sudo port deactivate healpix-cxx`), then reinstall healpy with pip so that it builds healpix_cxx itself without OpenMP support.

**Comment by svalenti** [comment]
Thanks Leo !
However, It seems I have actually a problem with matplotlib and anaconda that I need to fix

Referenced from: /Users/svalenti/anaconda/lib/python2.7/site-packages/matplotlib-1.5.0+918.gb6a79ac-py2.7-macosx-10.5-x86_64.egg/matplotlib/_path.so
  Expected in: dynamic lookup

**Comment by zonca** [comment]
closing now, please reopen if needed
