### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by dodelson** [healpy/healpy#351]
on mac osx 10.9.5, tried 
pip install --user healpy
and it worked, but then 
>python
>import healpy
leads to:
ImportError: dlopen(/Users/sdodelson/Library/Python/2.7/lib/python/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Symbol not found: _GOMP_barrier
  Referenced from: /opt/local/lib/libhealpix_cxx.0.dylib
  Expected in: flat namespace
 in /opt/local/lib/libhealpix_cxx.0.dylib

Any ideas?

**Comment by zonca** [comment]
We often find compilation issues on MAC OSX, the recommended way is to use Macports:

https://github.com/healpy/healpy/blob/master/INSTALL.rst

**Comment by lpsinger** [comment]
This error message usually means that there was a healpix_cxx library installed on your computer that was built with OpenMP acceleration, but healpy was built using a compiler that does not support OpenMP. Since it looks like you are using MacPorts anyway, I agree with @zonca with the suggestion to install healpy using MacPorts:

    $ sudo port install py27-healpy

Please re-open if this does not work for you.
