### ISSUE TITLE
AttributeError about __NUMPY_SETUP__ from setup.py

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#391]
@adl1995 and I are starting a Python project using `healpy`, and while getting set up we got this error:
```
  File "/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/easy_install-eq87v75w/healpy-1.10.3/setup.py", line 353, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```
Full log: https://travis-ci.org/hipspy/hips/jobs/236887749#L295

Now I think the issue is simply that we're missing `numpy` from the environment where we tried to `pip install healpy` (not sure yet, still looking). But even if that's the case: the error message could be improved, i.e. say "first install numpy" instead of an `AttributeError`?

**Comment by lpsinger** [comment]
No, it looks like Numpy was installed by Conda. This appears some lines earlier in your Travis output:

```
The following NEW packages will be INSTALLED:

    mkl:   2017.0.1-0   
    numpy: 1.12.1-py36_0
```

This is a very strange error message, because if you just open a new Python shell and type the line of code that is raising this exception, `__builtins__.__NUMPY_SETUP__ = False`, you will get no error message.

**Comment by pontoppi** [comment]
I'm having the same problem. Looks like this is an issue with the using __builtins__ as a dict when it's also a module. I think this means that healpy won't work with setuptools

See for instance: https://github.com/pycalphad/pycalphad/issues/26
