### ISSUE TITLE
map2alm then alm2map does odd things to the standard deviation

### ISSUE THREAD

**Issue by mpeel** [healpy/healpy#414]
I'm trying to do a monte carlo of the noise levels in WMAP / Planck maps (using Nobs and variance maps) in order to verify smoothed variance maps. However, the standard deviation that is being calculated after doing map2alm then alm2map is not the same as the input, even when no smoothing is being applied.

Reducing the code to its most basic, I am doing:

`import healpy as hp`
`import numpy as np`
`nside=64`
`npix=12*nside**2`
`map = np.random.normal(scale=1.0, size=npix)`
`print np.mean(map)`
`print np.median(map)`
`print np.std(map)`
`alms = hp.map2alm(map)`
`newmap = hp.alm2map(alms, nside)`
`print np.mean(newmap)`
`print np.median(newmap)`
`print np.std(newmap)`

The expected output of the last line is 1 - however, the code is returning ~0.86

**Comment by mreineck** [comment]
Yes, that's (unfortunately) expected behavior.

The discretized field you construct on the sphere is not band-limited, and therefore the map2alm -> alm2map chain will not reproduce the input.

If you need a band-limited map, you have to start with random numbers in lm space and transform these via alm2map.

With such an input, the accuracy of map2alm->alm2map should be quite good, depending on your choices of lmas, mmax and nside (for some typical values, see e.g. section 5.1 of https://arxiv.org/pdf/1010.2084).

**Comment by mpeel** [comment]
Thanks mreineck. I suggest adding this to the documentation to make this clear to others who try to do this. In this case I am running map2alm then almxfl to convolve with a window function before running alm2map, in that case I assume things are no longer band-limited provided that the beam area is larger than the pixel area.

**Comment by zonca** [comment]
@mpeel would you be able to add the documentation yourself via a Pull Request? Thanks!

**Comment by mpeel** [comment]
I *think* I've submitted a suitable pull request at https://github.com/healpy/healpy/pull/423 ... Sorry, this is not a system I'm familiar with!

**Comment by zonca** [comment]
very good thanks!

**Comment by mpeel** [comment]
Thank you for maintaining healpy!
