### ISSUE TITLE
Power spectrum from patches

### ISSUE THREAD

**Issue by orjuelajavier** [healpy/healpy#481]
Hello,
I want to ask you if it is possible to generate the CMB power spectrum from patches of 10x10 degrees of the sky in healpy.
I was trying to use  hp.anafast(map), but it only works with the entire map. 
Thank you.

**Comment by DanielLenz** [comment]
For general questions, we'd recommend the [healpy tag on stackoverflow](https://stackoverflow.com/questions/tagged/healpy), you'll likely reach a broader audience and receive a faster response.

That being said, there is built-in function to get the angular power spectrum for a specific patch.
Nonetheless, you can set up a mask by which you multiply your data and then compute the power spectrum for this masked map, i.e.

```python

nside = 512
npix = hp.nside2npix(nside)

glon, glat = hp.pix2ang(nside, np.arange(npix), lonlat=True)
mask = np.logical_and.reduce((
                                            glon > 40,
                                            glon < 50,
                                            glat > 60,
                                            glat  < 70))

Cl = hp.anafast(yourmap * mask)
```

Ideally, you also want to apodize your map before you do that. Otherwise, the sharp edges in map space will lead to oscillations in your power spectrum on small scales.

**Comment by orjuelajavier** [comment]
Thank you very much Daniel for your response. I would like to ask you one more question (sorry for don't ask in stackoverflow, next time I'll do!!). I have created a patch of 10x10dg^2  via hp.visufunc.cartview(), so actually what I really have is an  np.array of 256X256. Is there a way to transform this array into  a map format in order to use the command that you wrote previously?
Thanks

**Comment by DanielLenz** [comment]
I think the better thing to do is to go back to your original map from which you've extracted a 2D image via hp.cartview(), and use the `lonra` and `latra` ranges you've used for that to generate a full-sky mask.

**Comment by orjuelajavier** [comment]
Yes, I used that command. Thank you very much Daniel, I will follow your suggestion.
Regards,
Javier.
