### ISSUE TITLE
Plot vectors over a hp.mollview plot

### ISSUE THREAD

**Issue by pferreiraov** [healpy/healpy#556]
Hi, I'm trying to plot a hp.mollview map with some vectors connecting specified points over the sphere (giving the galactic coordinates of these points). 

I can plot these vectors over a mollview plot using matplotlib and the annotate function (any other idea to create these vectors?), but I cannot overlay this with the hp.mollview plot. There any healpy function or matplotlib function to make this happen?

# **The example code is here:**

`from mpl_toolkits.basemap import Basemap
import numpy as np
import healpy as hp
import matplotlib.pyplot as plt
m = Basemap(projection='moll',lon_0=0,resolution='h',celestial=True)
hp.mollview(np.arange(12))
hp.graticule()

m.drawparallels(np.arange(-90.,90.,30.),labels=[False,True,False,False])
m.drawmeridians(np.arange(0.,360.,30.))
m.drawmapboundary(fill_color='w')
phi = np.linspace(0, 2.*np.pi, 180)

aberror=np.array([15.7,29.6]);
dopperror=np.array([19.6,40.6]);
abdopperror=np.array([12.5,23.2]);

smicavec=np.array([0.00101131,-0.000102853,0.00122483])
lon,lat=hp.vec2ang(smicavec,lonlat=True)
lon=360-lon
marker='v';colorm='b';#title='S';
longerror1=aberror[1];laterror1=aberror[0];colore1='blue';
longerror2=2*aberror[1];laterror2=2*aberror[0];colore2='cyan'

x,y = m(lon, lat)
m.plot(x, y,marker,color=colorm,markersize=4,label='Aberration')
plt.text(x,y,title)
r1 =longerror1; r2 = laterror1;
x,y = m(lon + r1*np.cos(phi) , lat + r2*np.sin(phi))
m.plot(x, y, color=colore1)
r1 = longerror2; r2 = laterror2
x,y = m(lon + r1*np.cos(phi) , lat + r2*np.sin(phi))
m.plot(x, y, color=colore2)
x0,y0 = m(np.array([0,90,15,57,86,25]),np.array([0,-60,76,43,-29,4]))
x1,y1 = m(np.array([60,30,167,234,-21,16]),np.array([40,60,65,-11,82,-78]))
m.plot(x, y, color=colore2)
for i in range(6):
    plt.annotate('', xy=(x0[i], y0[i]), xytext=(x1[i], y1[i]),
            arrowprops=dict(facecolor='black',width=0.5,headwidth=6.0,headlength=6),
            )
ax = plt.gca()
ax.patch.set_alpha(0.5)
plt.show()`

# **The result is this plot (in pdf and in png low res)**

![test](https://user-images.githubusercontent.com/49214662/58384251-fe135a00-7fb5-11e9-9876-d928f0cbf085.png)

[test.pdf](https://github.com/healpy/healpy/files/3220498/test.pdf)

# **But I want something like that (which I made by hand, overlapping 2 plots using an image editor software):**

![biased_unbiased_intro](https://user-images.githubusercontent.com/49214662/58384272-3a46ba80-7fb6-11e9-8229-7f850df9ccd2.png)

Thanks!

**Comment by cjcopi** [comment]
I think you can do this within healpy without needing to use Basemap.

When you use `hp.mollview` an axes object is created that knows about the spherical projection, this axis should be usable to achieve your desired plot.  I cannot say exactly how since I always need to play around with a lot of reading documentation and trial and error.  However, the important things to know are to use the created axes objects and the existence of the projection methods.

Calling the axes object `hax`, there are methods with names`hax.proj.*` that do many conversions for you.  There are also methods like `hax.projplot` and `hax.projtext` that will handle plotting, etc, with the projection in mind, including converting between known coordinate systems (Galactic, Ecliptic, and Celestial) as well as arbitrary rotations.  There are key word arguments for dealing with astronomical versus geographic conventions, using latitude and longitude instead of spherical angles, etc.

As a simple example we can put a marker on plot using code like the following. There are many other ways this could be accomplished, however ....

To do coordinate system conversions it is necessary to create the map in a particular coordinate system. Since you mention SMICA I will take this to be Galactic.  The `smicavec` seems to be specified in Celestial coordinates.  I do not know that the axes we require is guaranteed to be the first one, so we look for it (and assume it is found!)

```
import numpy as np
import healpy as hp

nside = 1
npix = hp.nside2npix(nside)
hp.mollview(np.arange(npix), title='Pipelines - with boost factor', notext=True, coord='G')
hp.graticule()
f = plt.gcf()
for ax in f.get_axes() :
    if isinstance(ax, hp.projaxes.SphericalProjAxes) :
        hax = ax
        break
smicavec = np.array([0.00101131,-0.000102853,0.00122483])
lon,lat = hp.vec2ang(smicavec, lonlat=True)
hax.projplot(lon, lat, marker='v', color='b', ms=4, lonlat=True, coord='C')
```

**Comment by pferreiraov** [comment]
Thank you cjcopi. I found a solution after read you comment.

We can do it easily with the projection function "hp.projector.Mollweide Proj()".
Here an example:

```
import healpy as hp
import numpy as np
import matplotlib.pyplot as plt

nside = 4
npix = hp.nside2npix(nside)
hp.mollview(np.arange(npix), title='Pipelines - with boost factor', notext=True, coord='G')
hp.graticule()
    
def mollweid_vec(lat_start,long_start,lat_end,long_end,color,width,headwidth,headlength):
    proj = hp.projector.MollweideProj()
    plt.annotate('', xy=(proj.ang2xy(lat_end, long_end,lonlat=True)), xytext=(proj.ang2xy(lat_start, long_start,lonlat=True)),   arrowprops=dict(color=color,width=width,headwidth=headwidth,headlength=headlength))

mollweid_vec(90,30,-60,-60,'black',0.5,6,6)
mollweid_vec(10,45,120,-90,'orange',0.5,6,6)
mollweid_vec(-70,-45,30,110,'red',0.5,6,6)

plt.savefig('test.png')
```

That gives the output:

![test](https://user-images.githubusercontent.com/49214662/60319291-44a8fb00-994c-11e9-9c9d-380bca390874.png)

**Comment by zonca** [comment]
it looks like this was solved
