### ISSUE TITLE
Running anafast just on a specified l range - setting lmin and lmax

### ISSUE THREAD

**Issue by pferreiraov** [healpy/healpy#559]
Hi, is it possible to set not only lmax but a minimun l (lmin)?
I have to apply different functions over maps generated from different angular resolutions (bins on l space), but I'm losing to much time calculating anafast from 0 to lmax on a map where I want only the region 1900<=l<=2000 for example. 

Thanks!

**Comment by mreineck** [comment]
This functionality does not exist. It would not save you much time either, since during every anafast run the spherical harmonics are calculated by recurrences starting at l=m for every m and theta and working their way up to lmax. Storing them is not really an option either; at the band limits you mention, this would require tens of GB.

**Comment by pferreiraov** [comment]
I think this is because healpy uses the c version of healpix for anafast. On fortran's f90 version the l's and m's order is different, [[l=0],[[l=1,m=0],[l=1,m=1]],[[l=2,m=0],[l=2,m=1],[l=2,m=2]]...]. On healpy the a_lm order is different like you said. Maybe it's possible on the fortran anafast version.

**Comment by mreineck** [comment]
In fact, the ordering in memory is the same in Fortran and C/C++/Python ... it's just that the languages decide to write the indices down in different orders :)
All of our implementations perform the spherical harmonic transforms using the same algorithms, there is no shortcut in the Fortran version.
