### ISSUE TITLE
Masking effect on Spherical Harmonics

### ISSUE THREAD

**Issue by Cerciyes** [healpy/healpy#562]
While anafast calculating power spectrum, it deals with the mask (UNSEEN pixels) as putting 'zero's inside these pixels just before the calculation (I read this from healpy documentation --> https://healpy.readthedocs.io/en/1.12.9/generated/healpy.sphtfunc.map2alm.html). 
In our case, the mask is very large where the effective sky fraction is around 0.11. These zeros of course affecting the cross correlation result. Is there a way to neglect these masked pixels and only consider the unmasked pixels, so number of pixels in computation will be N_pix * f_sky ?

**Comment by mreineck** [comment]
Spherical harmonic analysis always requires a fully defined map, because every spherical harmonic coefficient depends on all pixel values. If we assume the value of some pixels as "unknown", we'd simply have no way to determine the monopole moment, for example.

**Comment by hivon** [comment]
Hi Martin, I guess the question is whether one can reduce the number of calculations by skipping
the pixels set to 0 (=unknown), knowing full well how this will affect the resulting multipoles.
It is to some extend possible in Healpix/F90 by ignoring the Healpix iso-latitude rings devoid of valid pixels (since the costly part the spherial harmonics depends on the rings latitude), but the saving
is not as good as f_sky, and will depend on the exact location of the valid pixels on the sphere.
In principle it could also be done in C++ and healpy.

**Comment by mreineck** [comment]
This is of course possible, but it would not change the fact that

> These zeros of course affecting the cross correlation result.

which I thought was the main concern.

**Comment by Cerciyes** [comment]
Besides the number of calculations, our main concern is the angular power spectrum result itself. Just because of the 'masked' definition, we would prefer the implementation that does not really account them, rather than putting zero. In that case, one needs to take into account of mixing matrix calculation to eliminate this masking effect, isn't it ?

**Comment by mreineck** [comment]
> In that case, one needs to take into account of mixing matrix calculation to eliminate this masking effect, isn't it ?

I expect so. It may be possible to run a full-sphere analysis for both the masked map and the mask itself and do something clever with the resulting two a_lm sets, but I don't have enough experience with this.

**Comment by hivon** [comment]
Mathematically putting some pixels to 0 is exactly the same as ignoring them since the spherical harmonics live on the whole sphere and you consider they scalar product with the signal.
As for the effect on the power spectrum, there is a big literature on the subject, and the best (and practical) methods depend on whether you are interested in large scales or small scales.
In any case, because of an Heisenberg-like relation, you will not be able to get back the exact individual C(l) as soon as you cut some pixels out, but you can try to minimize the error made.
As a starting point, you can have a look at the references http://www2.iap.fr/users/hivon/software/PolSpice/ or look at what was done in the Planck data analysis.

**Comment by Cerciyes** [comment]
Thanks for the references. I will check them.

**Comment by j-erler** [comment]
As far as I can tell the issue that has been brought up is due to a basic property of discrete Fourier- and spherical harmonic-transformations and regards the normalization that is used. Commonly, the transforms are normalized by the number of discrete samples (i.e. pixels) and the masked samples should be excluded here. It is correct that setting the masked pixels to 0 is the same as ignoring them when it comes to the shape of the computed power spectrum, but one should not forget that the zeros represent missing data, even if the computation requires valid floating point values. I created a figure to illustrate that the power spectrum of an artificial CMB map computed using all-sky data and using 10% of the sky will only match if the latter is re-normalized by 1/f_sky to account for the missing samples. When done so the computed spectrum will of course not contain valid information on the largest multipoles since no valid data is available, but for higher ell both spectra are supposed to match with the one computed from a small part of the sky carrying larger statistical uncertainty.

![masked_PS_example](https://user-images.githubusercontent.com/35317736/59045893-2e45dd00-8881-11e9-9f3b-9889a3751538.png)

**Comment by hivon** [comment]
If only it were that simple !
The fsky correction is only true at first order. Applying a cut sky couples the modes between them.
You will notice that your pink curve (masked C(l) / fsky) has a slow oscillation around the blue curve
(full sky C(l)) which a signature of the mask you applied.
Ignoring this fact will bias the cosmological parameters you would fit on the C(l).
If instead of using a CMB C(l), you used a mono-mode C(l) (ie, zero at all except say l=200) you would see some spurious C(l) everywhere.

**Comment by j-erler** [comment]
Thanks Eric for sharing your insights. I will have a look at your references as well. Has anyone considered to add the advanced features that are offered by e.g. PolSpice directly to healpy/healpix?

**Comment by DanielLenz** [comment]
There are already plenty of implementations available, such as Xpol, PolSpice, and most recently [PyMaster](https://namaster.readthedocs.io/en/latest/). Especially the latter is easy to install, well-documented, and has plenty of other great features.

**Comment by hivon** [comment]
Note also that PolSpice has a python interface (ispice.py) and that if a map with plenty of empty (=masked out) pixels is analyzed, some time will be saved by ignoring those pixels.
