### ISSUE TITLE
synfast raises 'invalid value for npix'

### ISSUE THREAD

**Issue by Christovis** [healpy/healpy#564]
I am trying to create a high-res CMB map from Cl's created with CLASS.
I use the following settings:
```
NSIDE = 23552
hp.sphtfunc.synfast(TT, NSIDE)
```

This however results in the following error:

> Error encountered at /cosma/local/software/Healpix_3.40/src/healpy/healpixsubmodule/src/cxx/autotools/Healpix_cxx/healpix_base.cc, line 46
> (function static I T_Healpix_Base<I>::npix2nside(I) [with I = int])

> invalid value for npix

> terminate called after throwing an instance of 'PlanckError'
> Aborted

I have tried different NSIDE values to see what the limit is, and found that the error message appears if NSIDE > 13312.
I know that it should be possible to go up to NSIDE=16384 (https://arxiv.org/abs/1706.01472) using HEALPIX.
Does anyone know a solution?

**Comment by mreineck** [comment]
With "normal" 32bit integers, the highest power-of-2 Nside value you can reach is 8192, non power-of-2 ones should go up to 13377, close to the value you mentioned. `healpy` and the C++ HEALPix library do not support map objects with higher Nside values; HEALPix C++ allows you to do computations like `ang2pix` at higher resolutions via the `Healpix_Base2` class, which uses 64-bit integers internally, but currently there is no `Healpix_Map2` class.

When the library was written, we considered Nside=8192 to be a reasonable upper limit for map size, since a map with that resolution already occupies at least 3.2GB of memory. Maybe we need to rethink this.

I do not know how the authors of the paper you are linking have performed their computations, but I'm pretty sure that they have modified the Healpix library to enable this.

**Comment by mreineck** [comment]
It seems that the code in the linked paper uses Fortran Healpix. In principle this should not support maps of such high Nside either, but it is possible that it "just works" through sheer luck. Further resolution increases will be problematic however.

**Comment by mreineck** [comment]
Also, are you aware that for a successful execution of

```
NSIDE = 23552
hp.sphtfunc.synfast(TT, NSIDE)
```

you would need at least 200GB of RAM (roughly)?

**Comment by Christovis** [comment]
The authors of my linked paper replied to an Email of mine:

> [...] we use Healpix Fortran90 subroutines in version 3.11 and did not have any trouble with Nside=16384.
> We used 64bit-integers in our code and did not modify the original Healpix scheme at all.
> But, the computation needed enough memory (>~ 100 GB).  [...]

**Comment by mreineck** [comment]
The potential problem I mentioned is the fact that array indices in Fortran are usually integers of "default" kind, and default kind is 32bit on almost any platform, as fas as I know. Also, Fortran integers are always signed.
The maximum number representable with this kind of integer is `2**31-1` (somewhere around 2 billion), and this is not enough to index all pixels in a Nside=16384 map. Since it still worked, the compiler must have treated the indices as unsigned integers internally, which is lucky and definitely not covered by the Fortran standard.

**Comment by SSB-bit** [comment]
I don't understand... I understand the layers and pixels but it needs a lot
of work... Bc the mask is heavy and almost completely changes the whole
entire look of what really is.    And can you explain or simplify the
meaning of execution of C(I) and what it means to be closed?

**Comment by Christovis** [comment]
@SSB-bit  
1.  the meaning of execution of C(I): I do not quite understand what you mean with 'execution of C(l)'.
2. why I close the issue: Because I thought the issue that raised the error message which I mentioned in my first post was found and explained. There is currently no solution for this issue, except that the software needs to be modified.

**Comment by SSB-bit** [comment]
We will all have to work together inorder to make the needed modifications
and inorder for them to be successful??
Correct??

**Comment by hivon** [comment]
To answer the questions about Healpix/F90: the F90 routines *do* support, by design, 
power-of-2 nside larger than 8192. 
The only exceptions being the cut sky IO routines.
So nside=16382 is not a problem, except for the large amount of memory required.

**Comment by mreineck** [comment]
OK, I see that we set the default integer type to 64bit when compiling. That should work on most platforms. I stand corrected.

**Comment by mreineck** [comment]
If maps of this size are becoming a more common scenario, it probably makes sense to change Healpix C++, merge `Healpix_Base` and `Healpix_Base2` and derive `Healpix_Map` from this new class.

This will be a big API change, however, and require changes to almost every software package using Healpix C++, so we should probably update the major version number to 4 when this happens.

**Comment by ntessore** [comment]
@mreineck To create a `Healpix_Map2`, is it "only" a matter of creating

    template<typename T, typename I> class T_Healpix_Map: public T_Healpix_Base<I>
    {
        typedef I index_type;

and replacing all interfaces that accept maps with something like

    template class<M>
    void myfunction(M& mymap, typename MapType::index_type myindex)

or are there algorithmic issues where larger int types would need special care?

**Comment by mreineck** [comment]
A few more changes are necessary, but not many. For example, the tables for in-place swapping between NEST and RING are only defined up to nside=8192. Beyond that, we either should throw an exception or use the out-of-place method of swapping.

**Comment by ntessore** [comment]
Thanks for the reply. If it turned out we absolutely needed this and I potentially looked into it, would it make sense to get in touch?

**Comment by boryanah** [comment]
Hi! Are there any updates on this issue -- I am also looking to create a high-resolution map with nside of 16384 and apply smoothing to it. If there is perhaps a beta version of this, I would be happy to be a guinea pig.
