### ISSUE TITLE
Create patch-of-sky instead of full-sky

### ISSUE THREAD

**Issue by Christovis** [healpy/healpy#565]
Would it be possible to include in a future release the option to initiate a patch-of-sky instead of the default full-sky array/map?

That would be beneficial for me, since I am running against the following problem:
[https://github.com/healpy/healpy/issues/564](url) 

I only need a 20deg^2 patch-of-sky at a resolution of  0.0024deg^2, which would mean to use an Nside of approx. 23k. For a full-sky this resolution is too high, and would be a waste, since in my case the majority of pixels are UNSEEN anyway.

**Comment by SSB-bit** [comment]
Makes perfect sense! So we have future plans then! ? :)

**Comment by mreineck** [comment]
The main problem with this is that everyone seems to expect slightly different things of a "partial map" data type, so it is extremely hard to provide something that everyone can use ...
For your situation (since you want to do harmonic analysis), the best format would be a range of HEALPix rings and the corresponding values. That would still be a waste, since you don't have values on the full rings, but harmonic analysis is only going to work on full rings anyway.
If this is roughly what you have in mind, you can probably already use the Python interface of [libsharp](https://github.com/libsharp/libsharp), but I admit that this is not as high-level as the rest of `healpy`.

**Comment by SSB-bit** [comment]
I'm working on it and I'm trying!

**Comment by lpsinger** [comment]
We are using the NUNIQ ordering for partial or mixed-resolution LIGO sky maps. You may want to look into https://emfollow.docs.ligo.org/userguide/tutorial/multiorder_skymaps.html.

**Comment by mreineck** [comment]
Unfortunately this probably won't meet  the needs here ... requested Nside is not a power of 2 and alm2map/map2alm require full rings.
