### ISSUE TITLE
Extremely confusing dtype defaults in fitsfunc

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#585]
Currently
-  the `dtype` argument of `write_map` defaults to `np.float32`,
-  the one of `read_map` defaults to `np.float64`,
-  the `one of `write_alm` is called `dtype_out` and defaults to `None`,
-  and the one of `read_alm` doesn't exist.

Furthermore, the `map` routines accept lists of types, and the `alm` routines appear to require scalars.

I can prepare a patch, but I don't know what a useful consensus would be. My suggestion is to introduce `None` for all functions and make this the default, but it will change the behaviour of many existing codes.

**Comment by crosset** [comment]
Some bit of history concerning the first two points: the idea was to save space when storing the maps on disk (assuming that usually don’t need more than 7 digits precision on your data) but putting data in a float64 array directly since you usually want to do computation (especially spherical harmonics transform) with double precision. I think I was inspired initially in these defaults by IDL healpix routines.
Of course, it can evolve to something more rational. Critical code should always specify explicitly the data type. A period with a warning (to announce the future change) before making the change could help the transition.

**Comment by mreineck** [comment]
I should also explain why I have become worried about this:

The reason was that a user:
- had a map in double precision
- stored it to disk (using default data types)
- loaded it from disk (again with defaults)
- made sure it was still double precision
- went on to make an accuracy comparison with another code.

This led to the incorrect result that Healpix map analysis performed much worse than the other algorithm, and that in turn was published on arxiv, and we were lucky to get to know about it and point out the mistake. The chance that a referee who is not very familiar with the Healpix software would have spotted this, are remote.

I don't think the user is to blame at any point there.

**Comment by zonca** [comment]
fixed in #586
