### ISSUE TITLE
adjoint synthesis

### ISSUE THREAD

**Issue by Gabriel-Ducrocq** [healpy/healpy#594]
Hi, 

I am trying to do an adjoint synthesis on a pixel map instead of an analysis. Is there a way to do this with healpy without dealing with libsharp ?
(I thought specifying the weights to be equal to one would do the trick, but it seems the user has no influence on it)

Thank you,
Gabriel.

**Comment by zonca** [comment]
you should be able to use `map2alm` and specify `use_weights=False`

**Comment by mreineck** [comment]
That's probably not enough, because even `map2alm` applies "first order" weighting, i.e. it multiplies its result by 4*pi/(12*nside**2). If you really want the adjoint of `alm2map`, you will have to divide by this factor again.

**Comment by Gabriel-Ducrocq** [comment]
Hi @zonca, @mreineck ,

Thanks for your answers, it seems to do the trick.
However, from what I understand from the answer of @zonca, when doing an analysis, I need to set `use_pixel_weights=True`. But this surprises me because `map2alm` sets `use_pixel_weights=False` by default... So I expcted this to be the right setting to perform an analysis. Am I missing something ?

**Comment by mreineck** [comment]
That's unfortunately sloppy use of language... `map2alm` always uses weights, there are just three different sets of them, which have different degrees of sophistication:
- when you don't specify any weights, the uniform weight value `4*pi/(12*nside**2)` is used
- with ring weights enabled, every ring is weighted with a uniform value similar to the one above
- with pixel weights, every pixel gets an individual weight

All of these approaches are approximations. There is no true, accurate "analysis" for all "normal" grids on the sphere, which is the inverse of the "synthesis" operation. It can't exist, since the matrix representing this transform is not square, and therefore cannot be inverted.
The only thing that's well defined is the adjoint synthesis ... unfortunately this is not what people typically need.

**Comment by Gabriel-Ducrocq** [comment]
Okay, that's very clear, thank you !
