### ISSUE TITLE
Can I just compute E-mode alm?

### ISSUE THREAD

**Issue by pltaylor16** [healpy/healpy#600]
I have an application where I only need to compute the E-modes. I need to do this many times, so computing the T and B harmonic coefficeints is dramatically slowing down my pipeline. Is there any easy way to do this? I had a look in sphfunct.py, but it didn't seem like there was an obvious way to do this.

**Comment by mreineck** [comment]
In principle the libsharp library used internally by Healpix allows to compute E- and B-modes, omitting the T-codes, but this will only result in a savings of maybe 20%. As far as I can tell from the healpy docs, this functionality isn't wrapped in healpy, however.
Separate computation of E- and B-modes is not supported, since most of the necessary calculations are common for both, and just computing one of the two isn't much faster than computing both.

**Comment by mreineck** [comment]
Just as an update: `ducc0` will soon get the ability to compute E-modes only. Should `healpy` switch do `ducc0` as a backend in the future, this will become possible.
