### ISSUE TITLE
Drop readthedocs

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#606]
@DanielLenz @lpsinger 

I cannot build `healpy` on readthedocs anymore.
I am not sure if readthedocs reduced the memory limits or conda started using more memory, but all my projects started hitting memory limits.

Now I switched all of them to using `pip` which uses less memory.

For `healpy` however I cannot get `autotools` to work.

Over the years readthedocs has been really painful to manage, because whenever we have build issues we both have to update travis and also readthedocs.
I wished to abandon it earlier but I cannot find a replacement for building multiple versions and hosting all of them.

But this is not worth all this work so my plan is:

* setup travis to also build the docs and push them to `healpy.github.io`
* have only docs of `master` available there
* keep healpy.readthedocs.io for older versions with notice on top to redirect to healpy.github.io

Thoughs?

**Comment by DanielLenz** [comment]
> Now I switched all of them to using pip which uses less memory.

I can very much relate to that; I've been using conda less and less over the past year or two because of memory issues and a very slow resolution of the dependencies.

I'm sure you've looked into this, but do you think it's possible to host older versions on healpy.github.io as well? I'm a bit afraid that we confuse people about where which version of the docs is. We can certainly add notices and redirects etc, but perhaps there is a way to avoid this issue altogether.

I fully agree though with dropping a tool that's been causing a large amount of issues that required a lot of time to resolve.

**Comment by zonca** [comment]
@DanielLenz see https://github.com/readthedocs/sphinx_rtd_theme/issues/868

**Comment by zonca** [comment]
I am going to try again with conda given https://blog.readthedocs.com/better-conda-support/

**Comment by zonca** [comment]
conda works fine with the larger amount of memory provided by readthedocs, see #613
