### ISSUE TITLE
ud_grade issue

### ISSUE THREAD

**Issue by RaelynSullivan** [healpy/healpy#748]
Using the Planck galactic mask from https://irsa.ipac.caltech.edu/data/Planck/release_2/ancillary-data/previews/HFI_Mask_GalPlane-apo0_2048_R2.00/index.html, with the field=2 (60% galactic mask), when going from NSIDE 2048 to NSIDE 64 the healpy ud_grade returns a map of zeros, but if I go down to 256, and then from 256 down to 64 it works as expected. This doesn't seem to occur for all masks (for example a mask with just a range of the galactic plane masked seems to work as expected). I have included a sample code below using the mask from the link above and a galactic range.  I am running healpy version 1.15.2. 

```import healpy as hp
import numpy as np
import matplotlib.pyplot as plt

mask=hp.read_map('HFI_Mask_GalPlane-apo0_2048_R2.00.fits', field=2)
mask_down=hp.ud_grade(mask,64)
mask_down2=hp.ud_grade(hp.ud_grade(mask,265),64)

hp.mollview(mask)
hp.mollview(mask_down)
hp.mollview(mask_down2)
plt.show()
#mask and mask_down2 will look as expected, mask_down will be all zeros

mask_gal_cut=np.zeros(hp.nside2npix(2048))
mask_gal_cut[hp.query_strip(2048, np.pi/2-np.radians(10), np.pi/2+np.radians(10))] = 1
mask_gal_cut_down=hp.ud_grade(mask_gal_cut,64)
hp.mollview(mask_gal_cut)
hp.mollview(mask_gal_cut_down)
plt.show()
#mask_gal_cut and mask_gal_cut_down both look as expected

**Comment by zonca** [comment]
the problem is that the mask you read is `uint8`:

    mask.dtype
    dtype('uint8')

this is a short form of integers that saves memory and disk space but can cause computing issue as the one you found.

You need to cast to something else, for example a normal integer:

    hp.mollview(hp.ud_grade(mask.astype(int), 64))

![image](https://user-images.githubusercontent.com/383090/158000541-17d14644-8385-46e9-b5a8-386f55c03421.png)

Or you can cast the map to int when you read it:

mask=hp.read_map('HFI_Mask_GalPlane-apo0_2048_R2.00.fits', field=2, dtype=int)
