### ISSUE TITLE
Calling max_pixrad with non-power-of-2 nside crashes python

### ISSUE THREAD

**Issue by erykoff** [healpy/healpy#773]
Running the following two lines:
```
import healpy as hp
hp.max_pixrad(100)
```
Crashes with:
```
Error encountered at healpix_base.cc, line 746
(function void T_Healpix_Base<long long>::SetNside(I, Healpix_Ordering_Scheme) [I = long long])

SetNside: nside must be power of 2 for nested maps

libc++abi: terminating with uncaught exception of type PlanckError
zsh: abort      ipython
```
I _think_ this is an erroneous check, and that `max_pixrad` should work for any (positive) nside.  Certainly, it should not crash with an uncaught exception.

**Comment by mreineck** [comment]
That looks like an oversight in https://github.com/healpy/healpy/blob/fa03219ed309bb99a0dd1e3e0834d074a7f7915e/healpy/src/_healpy_pixel_lib.cc#L381
I think if RING is used there instead of NEST, everything should work fine; `max_pixrad` itself is agnostic to the ordering scheme, but for some nside values, a `Healpix_Base` object can only be constructed in RING scheme..

**Comment by zonca** [comment]
fixed in https://github.com/healpy/healpy/pull/777
