### ISSUE TITLE
Add convenience functions, map2cl and cl2map 

### ISSUE THREAD

**Issue by Sebastian-Belkner** [healpy/healpy#781]
Hi,

is there any chance we can have these, similar to the conventions of the other transformers,

- `map2alm`, `alm2map`, `alm2cl`, `cl2alm`?

Would appreciate it, could just be a copy of `anafast `and `synfast ` and have both? 

^Seb

**Comment by mreineck** [comment]
I think `cl2map` could be fine, but I have some reservations against `map2cl`, since `map2alm` itself is not very well defined already. In some contexts, it is used as "an approximate inverse of `alm2map`", and in others it means "the adjoint operation of `alm2map`, scaled by some factor" (which is unfortunately not the same). Personally I'd prefer to see `map2alm` deprecated and replaced by `adjoint_alm2map` and (perhaps) `map_analysis`.

**Comment by zonca** [comment]
we might reconsider this in the future if we do a major refactoring of the code.
