### ISSUE TITLE
Unexpected results healpy.pixelfunc_get_interp_weights

### ISSUE THREAD

**Issue by JegerBroxterman** [healpy/healpy#832]
I am having difficulties understanding the healpy angular coordinate convention and the way it deals with coordinates not in the standard domains. As I understand, the angular coordinates theta and phi measure the colatitude southward from the north pole ([0,pi]) and longitude eastward ([0, 2*pi]), respectively. I am interpolating the coordinates but find confusing results. For example, determining

```
    nside = 4096
    healpy.pixelfunc.get_interp_weights(nside,0.67,1.56,lonlat=False)
```

gives  ` (array([21750286, 21750287, 21763479, 21763480]), array([0.07088279, 0.3518802 , 0.1007502 , 0.47648682]))`

However, when I use 
`    healpy.pixelfunc.get_interp_weights(nside,0.67-np.pi,1.56,lonlat=False)`
this yields `  (array([179563065, 179563066, 179576258, 179576259]), array([0.1007502 , 0.47648682, 0.07088279, 0.3518802 ]))`

The weights are the same but in a different order and different neighboring pixels. Confusingly, `healpy.pixelfunc.get_interp_weights(nside,0.67-2*np.pi,1.56,lonlat=False)` does give exactly the same results as the first option. Should not all these three options give the same results or is there something in the way the angles are converted that I don't understand?

**Comment by mreineck** [comment]
In your calls you are passing first a co-latitude of `0.67` and then one of `0.67-np.pi`. These are definitely referring to different locations on the sphere (since you leave the longitude unchanged, they refer to exactly opposing locations on the sphere). So it's expected that you get different pixel indices.

If you change the colatitude by 2pi, you do on full circle around the sphere and arrive at the original location again. 

Perhaps the confusing thing is that the "regular" range of the co-latitude is [0;pi], but it doesn't have a periodicity of pi, but rather of 2pi. Once you have gone from the north to the south pole, you need to com back to the north pole first before everything repeats, and that happens in the theta range [pi;2pi].

**Comment by JegerBroxterman** [comment]
Thank you. This clears up my confusion regarding the periodicity.
