### ISSUE TITLE
Will healpy migrate to ducc0 for faster spherical harmonic transforms?

### ISSUE THREAD

**Issue by dreamthreebs** [healpy/healpy#977]
Hi healpy developers,

Thanks for all your hard work on maintaining such an essential package for the scientific community!

I was wondering if there are any plans to migrate `healpy` to use [ducc0](https://gitlab.mpcdf.mpg.de/mtr/ducc) for spherical harmonic transforms (SHT). Since `ducc0` is known for its speed and efficiency in SHT, it seems like it could provide a significant performance boost for `healpy`.

Would love to hear your thoughts on this!

**Comment by mreineck** [comment]
Hi,

it's true that I'm no longer actively working on `libsharp`, which provides the SHTs for `healpy`, and instead moved to `ducc0`, but `ducc0`'s SHTs are not significanly faster than those in `libsharp` ... there may be a 10-20% difference in some places, but really nothing earth-shaking. If you notice bigger differences, I'm fairly sure this is caused by compilation without native optimizations. I'd be happy to have a closer look if you have concrete examples.

Having said that, I'm all for `healpy`'s migration to `ducc0` at some point; it's just quite a big task.

**Comment by dreamthreebs** [comment]
Thank you for your clarification, I notice the similar issues in #717 so I will close this issue. I am doing some calculations on needlets internal linear combination and many realizations are needed for noise debias and standard deviation computions. In that situation, little improvement on spherical transformation can benefit a lot. Hope to see migration to `ducc0` for healpy.

**Comment by mreineck** [comment]
Here is a couple of things to try if you want to optimize the SHT performance in `healpy`:
- Install `healpy` from sources following the instructions in https://github.com/healpy/healpy/blob/main/INSTALL.rst#generating-native-binaries, instead of just installing the binary package. This will almost certainly make the SHTs much faster
- Play around with the environment variable `OMP_NUM_THREADS`. It is ususlly set to the number of virtual cores on your CPU. Under some circumstances your timings may be better if you set this to te number of actual CPU cores.

**Comment by mreineck** [comment]
An alternative is to configure `cfitsio` using `./configure --disable-curl`. That should also get rid of the complicated dependencies.

**Comment by mreineck** [comment]
You can, but it is not entirely straightforward:
- the HEALpix geometry is not directly supported by the transforms; you need to use small adaptor functions (see below for an example)
- polarized transforms are not done in a single call, but in a separate spin-0 call (for I/T), and a spin-2 call (for QU/EB).
- `ducc0` does not have a real equivalent to `healpy`'s `map2alm`, since the meaning of this function is only vaguely defined. It tries to compute an approximate inverse to `alm2map`, but since the SHT does not correspond to a square matrix, this will never really work. Instead, `ducc0` offers the adjoint (instead of inverse) method to `alm2map`.

Some adapter code:

```Python
def alm2map(alm, nside, lmax):
    base = ducc0.healpix.Healpix_Base(nside, "RING")
    geom = base.sht_info()
    return ducc0.sht.synthesis(alm=alm.reshape((1,-1)),
                               lmax=lmax,
                               spin=0,
                               nthreads=nthreads, **geom).reshape((-1,))


def alm2map_adjoint(map, nside, lmax):
    base = ducc0.healpix.Healpix_Base(nside, "RING")
    geom = base.sht_info()
    return ducc0.sht.adjoint_synthesis(map=map.reshape((1,-1)),
                                       lmax=lmax,
                                       spin=0,
                                       nthreads=nthreads, **geom).reshape((-1,))
```

**Comment by dreamthreebs** [comment]
Thanks, learned a lot!
